name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for MCprep! We just need some info
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
    - type: textarea
      id: steps-to-reproduce
      attributes:
        label: What steps are needed to produce the bug?
        placeholder: Tell us what you did!
        value: "Step 1: "
      validations:
        required: true
  - type: dropdown
    id: version
    attributes:
      label: MCprep Version
      description: What version of MCprep are you using?
      options:
        - 3.3.1 (Default)
        - 3.3.0 
        - 3.2.5.1
        - 3.2.5
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Blender Version
      description: What version of Blender are you using?
      options:
        - 3.2
        - 3.1 
        - 2.93
        - 2.92
        - 2.91
        - 2.90
        - 2.83
        - 2.82
        - 2.81
        - 2.80
        - 2.79
        - 2.78
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: By submitting this issue, you have confirmed that you have filled out all the info needed.
      options:
        - label: I have given some details regading the bug and have also given the steps needed to reproduce the bug
          required: true
