name: Feature Request
description: File a feature request
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest new features for MCprep! All feature requests will be reviewed and responded to with an expectation of how likely it will be implemented after review.

  - type: checkboxes
    id: check-existing
    attributes:
      label: Check against existing requests
      description: Please check that your feature request is not [already listed here](https://github.com/TheDuckCow/MCprep/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) - if it is, then please comment on one of those issues instead. Duplicate request issues will simply be closed.
      options:
        - label: I have checked known issues, and my problem is different
          required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Describe the context
      description: What problem do you want solved? What are you trying to do? A clearly defined problem can help us come up with the best solution, not just the first solution to come to mind.
    validations:
      required: true

  - type: textarea
    id: feature-idea
    attributes:
      label: How do you imagine your feature works?
      description: In context would this feature happen? How would it do it? What inputs are needed from the user? What is the ending state, and how does the solve the problem identified above?
    validations:
      required: true

  - type: textarea
    id: existing-workarounds
    attributes:
      label: What existing workaround (or closest thing to a workaround) do you have today (within Blender, MCprep, or any software)? If there is no workaround, explain why you feel this way.
    validations:
      required: true
